// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sofa.CourseManagement.Infrastructure.Persistence;

#nullable disable

namespace Sofa.CourseManagement.Infrastructure.Migrations
{
    [DbContext(typeof(CourseManagementDbContext))]
    [Migration("20250223175854_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.CourseLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CourseLanguage", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.CoursePlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseId1");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CoursePlacement", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.CoursePlacementQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlacementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("coursePlacementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PlacementId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("coursePlacementId");

                    b.ToTable("CoursePlacementQuestion", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.CourseUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("CourseUser", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InstituteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InstituteId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("InstituteId");

                    b.HasIndex("InstituteId1");

                    b.ToTable("Field", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.FieldQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FieldId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("FieldId1");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("FieldQuestion", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.FieldQuestionChoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FieldQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAnswer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FieldQuestionId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("FieldQuestionChoice", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.LessonPlans.LessonPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SessionId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseLanguageId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId1");

                    b.ToTable("LessonPlan", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.PostBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LessonPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LessonPlanId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("LessonPlanId");

                    b.HasIndex("LessonPlanId1");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("PostBase", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.PostQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("QuestionId");

                    b.ToTable("PostQuestion", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseId1");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Session", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Users.InstituteUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InstituteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("InstituteId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("InstituteUser", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Institute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Institutes");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.ImagePost", b =>
                {
                    b.HasBaseType("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.PostBase");

                    b.ToTable("ImagePost", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.SoundPost", b =>
                {
                    b.HasBaseType("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.PostBase");

                    b.ToTable("SoundPost", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.TextPost", b =>
                {
                    b.HasBaseType("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.PostBase");

                    b.ToTable("TextPost", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.VideoPost", b =>
                {
                    b.HasBaseType("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.PostBase");

                    b.ToTable("VideoPost", (string)null);
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.Course", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Field", null)
                        .WithMany("Courses")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Title");

                            b1.HasKey("CourseId");

                            b1.ToTable("Course");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.AgeRange", "AgeRange", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("AgeRangeTitle");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("AgeRange");

                            b1.HasKey("CourseId");

                            b1.ToTable("Course");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.Navigation("AgeRange");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.CourseLanguage", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.Course", null)
                        .WithMany("CourseLanguages")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Language", "Language", b1 =>
                        {
                            b1.Property<Guid>("CourseLanguageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasMaxLength(50)
                                .HasColumnType("int")
                                .HasColumnName("Language");

                            b1.HasKey("CourseLanguageId");

                            b1.ToTable("CourseLanguage");

                            b1.WithOwner()
                                .HasForeignKey("CourseLanguageId");
                        });

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.CoursePlacement", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.Course", null)
                        .WithMany("Placements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId1");

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("CoursePlacementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Title");

                            b1.HasKey("CoursePlacementId");

                            b1.ToTable("CoursePlacement");

                            b1.WithOwner()
                                .HasForeignKey("CoursePlacementId");
                        });

                    b.Navigation("Course");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.CoursePlacementQuestion", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.CoursePlacement", null)
                        .WithMany("Questions")
                        .HasForeignKey("PlacementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.FieldQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.CoursePlacement", "coursePlacement")
                        .WithMany("_questions")
                        .HasForeignKey("coursePlacementId");

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.OrderNumber", "Order", b1 =>
                        {
                            b1.Property<Guid>("CoursePlacementQuestionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<short>("Value")
                                .HasColumnType("smallint")
                                .HasColumnName("Order");

                            b1.HasKey("CoursePlacementQuestionId");

                            b1.ToTable("CoursePlacementQuestion");

                            b1.WithOwner()
                                .HasForeignKey("CoursePlacementQuestionId");
                        });

                    b.Navigation("Order");

                    b.Navigation("Question");

                    b.Navigation("coursePlacement");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.CourseUser", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.Course", null)
                        .WithMany("CourseUsers")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sofa.CourseManagement.Domain.Users.User", null)
                        .WithMany("CourseUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sofa.CourseManagement.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Field", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Institute", null)
                        .WithMany("Fields")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId1");

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("FieldId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Title");

                            b1.HasKey("FieldId");

                            b1.ToTable("Field");

                            b1.WithOwner()
                                .HasForeignKey("FieldId");
                        });

                    b.Navigation("Institute");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.FieldQuestion", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Field", null)
                        .WithMany("Questions")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId1");

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Content", "Content", b1 =>
                        {
                            b1.Property<Guid>("FieldQuestionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Content");

                            b1.HasKey("FieldQuestionId");

                            b1.ToTable("FieldQuestion");

                            b1.WithOwner()
                                .HasForeignKey("FieldQuestionId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("FieldQuestionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Title");

                            b1.HasKey("FieldQuestionId");

                            b1.ToTable("FieldQuestion");

                            b1.WithOwner()
                                .HasForeignKey("FieldQuestionId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Level", "Level", b1 =>
                        {
                            b1.Property<Guid>("FieldQuestionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LevelTitle");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Level");

                            b1.HasKey("FieldQuestionId");

                            b1.ToTable("FieldQuestion");

                            b1.WithOwner()
                                .HasForeignKey("FieldQuestionId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.QuestionType", "Type", b1 =>
                        {
                            b1.Property<Guid>("FieldQuestionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("TypeTitle");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Type");

                            b1.HasKey("FieldQuestionId");

                            b1.ToTable("FieldQuestion");

                            b1.WithOwner()
                                .HasForeignKey("FieldQuestionId");
                        });

                    b.Navigation("Content");

                    b.Navigation("Field");

                    b.Navigation("Level");

                    b.Navigation("Title");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.FieldQuestionChoice", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.FieldQuestion", null)
                        .WithMany("QuestionChoices")
                        .HasForeignKey("FieldQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Content", "Content", b1 =>
                        {
                            b1.Property<Guid>("FieldQuestionChoiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Content");

                            b1.HasKey("FieldQuestionChoiceId");

                            b1.ToTable("FieldQuestionChoice");

                            b1.WithOwner()
                                .HasForeignKey("FieldQuestionChoiceId");
                        });

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.LessonPlans.LessonPlan", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.CourseLanguage", "CourseLanguage")
                        .WithMany()
                        .HasForeignKey("CourseLanguageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Sessions.Session", null)
                        .WithMany("LessonPlans")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Sessions.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId1");

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("LessonPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Title");

                            b1.HasKey("LessonPlanId");

                            b1.ToTable("LessonPlan");

                            b1.WithOwner()
                                .HasForeignKey("LessonPlanId");
                        });

                    b.Navigation("CourseLanguage");

                    b.Navigation("Session");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.PostBase", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.LessonPlans.LessonPlan", null)
                        .WithMany("Posts")
                        .HasForeignKey("LessonPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.LessonPlans.LessonPlan", "LessonPlan")
                        .WithMany()
                        .HasForeignKey("LessonPlanId1");

                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.PostQuestion", "Question")
                        .WithOne()
                        .HasForeignKey("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.PostBase", "QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Content", "Content", b1 =>
                        {
                            b1.Property<Guid>("PostBaseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Content");

                            b1.HasKey("PostBaseId");

                            b1.ToTable("PostBase");

                            b1.WithOwner()
                                .HasForeignKey("PostBaseId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.OrderNumber", "Order", b1 =>
                        {
                            b1.Property<Guid>("PostBaseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<short>("Value")
                                .HasColumnType("smallint")
                                .HasColumnName("Order");

                            b1.HasKey("PostBaseId");

                            b1.ToTable("PostBase");

                            b1.WithOwner()
                                .HasForeignKey("PostBaseId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("PostBaseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Title");

                            b1.HasKey("PostBaseId");

                            b1.ToTable("PostBase");

                            b1.WithOwner()
                                .HasForeignKey("PostBaseId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.ContentType", "ContentType", b1 =>
                        {
                            b1.Property<Guid>("PostBaseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ContentTypeTitle");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("ContentType");

                            b1.HasKey("PostBaseId");

                            b1.ToTable("PostBase");

                            b1.WithOwner()
                                .HasForeignKey("PostBaseId");
                        });

                    b.Navigation("Content");

                    b.Navigation("ContentType");

                    b.Navigation("LessonPlan");

                    b.Navigation("Order");

                    b.Navigation("Question");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.PostQuestion", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.FieldQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Priority", "Priority", b1 =>
                        {
                            b1.Property<Guid>("PostQuestionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Priority");

                            b1.HasKey("PostQuestionId");

                            b1.ToTable("PostQuestion");

                            b1.WithOwner()
                                .HasForeignKey("PostQuestionId");
                        });

                    b.Navigation("Priority");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Sessions.Session", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.Course", null)
                        .WithMany("Sessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId1");

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Title");

                            b1.HasKey("SessionId");

                            b1.ToTable("Session");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.OccurredDate", "OccurredDate", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset?>("Value")
                                .IsRequired()
                                .HasMaxLength(34)
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("OccurredDate");

                            b1.HasKey("SessionId");

                            b1.ToTable("Session");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("Course");

                    b.Navigation("OccurredDate");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Users.InstituteUser", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Institute", "Institute")
                        .WithMany("InstituteUsers")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sofa.CourseManagement.Domain.Users.User", null)
                        .WithMany("InstituteUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sofa.CourseManagement.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("Institute");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Institute", b =>
                {
                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("InstituteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Title");

                            b1.HasKey("InstituteId");

                            b1.ToTable("Institutes");

                            b1.WithOwner()
                                .HasForeignKey("InstituteId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("InstituteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Address_State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Address_Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Address_ZipCode");

                            b1.HasKey("InstituteId");

                            b1.ToTable("Institutes");

                            b1.WithOwner()
                                .HasForeignKey("InstituteId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.Code", "Code", b1 =>
                        {
                            b1.Property<Guid>("InstituteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Code");

                            b1.HasKey("InstituteId");

                            b1.ToTable("Institutes");

                            b1.WithOwner()
                                .HasForeignKey("InstituteId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Institutes.ValueObjects.WebsiteUrl", "WebsiteUrl", b1 =>
                        {
                            b1.Property<Guid>("InstituteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("WebsiteUrl");

                            b1.HasKey("InstituteId");

                            b1.ToTable("Institutes");

                            b1.WithOwner()
                                .HasForeignKey("InstituteId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Code");

                    b.Navigation("Title");

                    b.Navigation("WebsiteUrl");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Users.User", b =>
                {
                    b.OwnsOne("Sofa.CourseManagement.Domain.Users.ValueObjects.Name", "FirstName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FirstName");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Users.ValueObjects.Name", "LastName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LastName");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Users.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Users.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("nvarchar(13)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Users.ValueObjects.UserLevel", "Level", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LevelTitle");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Level");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Users.ValueObjects.UserName", "UserName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("UserName");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Sofa.CourseManagement.Domain.Users.ValueObjects.UserRole", "Role", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("RoleTitle");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Role");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email");

                    b.Navigation("FirstName");

                    b.Navigation("LastName");

                    b.Navigation("Level");

                    b.Navigation("PhoneNumber");

                    b.Navigation("Role");

                    b.Navigation("UserName");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.ImagePost", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.PostBase", null)
                        .WithOne()
                        .HasForeignKey("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.ImagePost", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.SoundPost", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.PostBase", null)
                        .WithOne()
                        .HasForeignKey("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.SoundPost", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.TextPost", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.PostBase", null)
                        .WithOne()
                        .HasForeignKey("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.TextPost", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.VideoPost", b =>
                {
                    b.HasOne("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.PostBase", null)
                        .WithOne()
                        .HasForeignKey("Sofa.CourseManagement.Domain.Institutes.Entities.Posts.VideoPost", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.Course", b =>
                {
                    b.Navigation("CourseLanguages");

                    b.Navigation("CourseUsers");

                    b.Navigation("Placements");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Courses.CoursePlacement", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("_questions");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Field", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.FieldQuestion", b =>
                {
                    b.Navigation("QuestionChoices");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.LessonPlans.LessonPlan", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Entities.Sessions.Session", b =>
                {
                    b.Navigation("LessonPlans");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Institutes.Institute", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("InstituteUsers");
                });

            modelBuilder.Entity("Sofa.CourseManagement.Domain.Users.User", b =>
                {
                    b.Navigation("CourseUsers");

                    b.Navigation("InstituteUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
